### ISSUE TITLE
Sync issue between devices / TF code - AWS UI [Troubleshooting]

### ISSUE THREAD

**Issue by ilyesedina** [ilyesedina/Terraform#13]
When I run terraform apply on my own computer, then run it on another PC, it doesn't recognize that the resources have been created.

The same issue occurs when I make changes on the AWS UI; it doesn't necessarily track the differences. For example, I added a tag under an EC2 instance, but it didn't show up in the terminal when running `terraform plan -refresh-only`

Video 41
Please review and let me know if any further adjustments are needed.

**Comment by ilyesedina** [comment]
Recognizes the changes from work PC

**Comment by ilyesedina** [comment]
On one of the VPC the changes has been recognized, and on the other one it wasn't. 
Root cause: The two VPC uses two different state file.

**Comment by dkEdiIly** [comment]
This issue has accrued now at the second time. 
Error message:
```
│ Error: creating EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
│       status code: 400, request id: 0685.. 
│
│   with aws_vpc.vpc,
│   on main.tf line 6, in resource "aws_vpc" "vpc":
│    6: resource "aws_vpc" "vpc" {
```
On the Aws Console I can see multiple resource created with the same name: demo_vpc
Last time I have manually removed the some of the vpc,

Possible errors:
- not tracking it is the same renounce   
- not being to migrate sate
